title: "MicroEntrepreneur"
description: "Cr√©ez en quelques minutes un shop immersif regroupant tous vos liens d'affiliation sous forme de produits"
opengraph_cover: 'opengraph-cover.jpg'
twitter_cover: 'twitter-cover.jpg'
twitter_account: '@ayaz__ac'
